<script
	data-cfasync="false"
	src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"
></script>

<h4 class="header"><a href="/">I Love Conference</a></h4>

<h5 class="header">Privacy Policy</h5>

<p>Last updated: April 18, 2023</p>
<p>
	This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of
	Your information when You use the Service and tells You about Your privacy rights and how the law
	protects You.
</p>
<p>
	We use Your Personal data to provide and improve the Service. By using the Service, You agree to
	the collection and use of information in accordance with this Privacy Policy. This Privacy Policy
	has been created with the help of the <a
		href="https://www.termsfeed.com/privacy-policy-generator/"
		rel="noreferrer">TermsFeed Privacy Policy Generator</a
	>.
</p>
<h1>Interpretation and Definitions</h1>
<h2>Interpretation</h2>
<p>
	The words of which the initial letter is capitalized have meanings defined under the following
	conditions. The following definitions shall have the same meaning regardless of whether they
	appear in singular or in plural.
</p>
<h2>Definitions</h2>
<p>For the purposes of this Privacy Policy:</p>
<ul>
	<li>
		<p>
			<strong>Account</strong> means a unique account created for You to access our Service or parts
			of our Service.
		</p>
	</li>
	<li>
		<p>
			<strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control
			with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest
			or other securities entitled to vote for election of directors or other managing authority.
		</p>
	</li>
	<li>
		<p>
			<strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot;
			or &quot;Our&quot; in this Agreement) refers to geneFUN, Inc., PO Box 11, Vineyard, UT 84059.
		</p>
	</li>
	<li>
		<p>
			<strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any
			other device by a website, containing the details of Your browsing history on that website among
			its many uses.
		</p>
	</li>
	<li>
		<p><strong>Country</strong> refers to: Utah, United States</p>
	</li>
	<li>
		<p>
			<strong>Device</strong> means any device that can access the Service such as a computer, a cellphone
			or a digital tablet.
		</p>
	</li>
	<li>
		<p>
			<strong>Personal Data</strong> is any information that relates to an identified or identifiable
			individual.
		</p>
	</li>
	<li>
		<p><strong>Service</strong> refers to the Website.</p>
	</li>
	<li>
		<p>
			<strong>Service Provider</strong> means any natural or legal person who processes the data on behalf
			of the Company. It refers to third-party companies or individuals employed by the Company to facilitate
			the Service, to provide the Service on behalf of the Company, to perform services related to the
			Service or to assist the Company in analyzing how the Service is used.
		</p>
	</li>
	<li>
		<p>
			<strong>Usage Data</strong> refers to data collected automatically, either generated by the use
			of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
		</p>
	</li>
	<li>
		<p>
			<strong>Website</strong> refers to I Love Conference, accessible from
			<a href="https://iloveconference.org">https://iloveconference.org</a>
		</p>
	</li>
	<li>
		<p>
			<strong>You</strong> means the individual accessing or using the Service, or the company, or other
			legal entity on behalf of which such individual is accessing or using the Service, as applicable.
		</p>
	</li>
</ul>
<h1>Collecting and Using Your Personal Data</h1>
<h2>Types of Data Collected</h2>
<h3>Personal Data</h3>
<p>
	We do not collect personally identifiable information (Personal Data) about You. We store a
	one-way <em>hash</em> of your IP address and browser and mobile device characteristics in order to
	distinguish Your usage of the website from the usage of other users in the Usage Data. This hash cannot
	be used to identify You personally.
</p>
<h3>Usage Data</h3>
<p>
	Usage Data is collected automatically when You use the Service. Usage Data may include information
	such as
</p>
<ul>
	<li>the pages of our Service that You visit,</li>
	<li>the queries that You submit,</li>
	<li>the ratings that You provide,</li>
	<li>the time and date of Your visit,</li>
	<li>the time spent on those pages, and</li>
	<li>other diagnostic data.</li>
</ul>
<h3>Use of Usage Data</h3>
<p>The Company may use Usage Data for the following purposes:</p>
<ul>
	<li>
		<p>
			<strong>To provide and maintain our Service</strong>, including to monitor the usage of our
			Service.
		</p>
	</li>
	<li>
		<p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>
	</li>
	<li>
		<p>
			<strong>For other purposes</strong>: We may use Your information for other purposes, such as
			data analysis, identifying usage trends, determining the effectiveness of our promotional
			campaigns and to evaluate and improve our Service, products, services, marketing and your
			experience.
		</p>
	</li>
</ul>
<h3>Tracking Technologies and Cookies</h3>
<p>We do not use Cookies or similar tracking technologies.</p>
<h1>Children's Privacy</h1>
<p>
	Our Service does not address anyone under the age of 13. We do not knowingly collect personally
	identifiable information from anyone under the age of 13. If You are a parent or guardian and You
	are aware that Your child has provided Us with Personal Data, please contact Us. If We become
	aware that We have collected Personal Data from anyone under the age of 13 without verification of
	parental consent, We take steps to remove that information from Our servers.
</p>
<p>
	If We need to rely on consent as a legal basis for processing Your information and Your country
	requires consent from a parent, We may require Your parent's consent before We collect and use
	that information.
</p>
<h1>Links to Other Websites</h1>
<p>
	Our Service may contain links to other websites that are not operated by Us. If You click on a
	third party link, You will be directed to that third party's site. We strongly advise You to
	review the Privacy Policy of every site You visit.
</p>
<p>
	We have no control over and assume no responsibility for the content, privacy policies or
	practices of any third party sites or services.
</p>
<h1>Changes to this Privacy Policy</h1>
<p>
	We may update Our Privacy Policy from time to time. We will notify You of any changes by posting
	the new Privacy Policy on this page.
</p>
<p>
	You are advised to review this Privacy Policy periodically for any changes. Changes to this
	Privacy Policy are effective when they are posted on this page.
</p>
<h1>Contact Us</h1>
<p>If you have any questions about this Privacy Policy, You can contact us:</p>
<ul>
	<li>By email: dallan@gmail.com</li>
</ul>
